//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHPDecision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternativaKriterij
    {
        public int alternativa { get; set; }
        public int kriterij { get; set; }
        public string stvarnaVrijednost { get; set; }
        public Nullable<double> izracunataVrijednost { get; set; }
    
        public virtual Alternativa Alternativa1 { get; set; }
        public virtual Kriterij Kriterij1 { get; set; }
    }
}
