//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHPDecision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alternativa()
        {
            this.AlternativaKriterijs = new HashSet<AlternativaKriterij>();
            this.UsporedbaAlternativaPremaKriterijus = new HashSet<UsporedbaAlternativaPremaKriteriju>();
            this.UsporedbaAlternativaPremaKriterijus1 = new HashSet<UsporedbaAlternativaPremaKriteriju>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<int> projekt { get; set; }
        public Nullable<double> vrijednost { get; set; }
        public bool obrisana { get; set; }
    
        public virtual Projekt Projekt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternativaKriterij> AlternativaKriterijs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsporedbaAlternativaPremaKriteriju> UsporedbaAlternativaPremaKriterijus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsporedbaAlternativaPremaKriteriju> UsporedbaAlternativaPremaKriterijus1 { get; set; }
    }
}
