//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHPDecision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kriterij
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kriterij()
        {
            this.AlternativaKriterijs = new HashSet<AlternativaKriterij>();
            this.Kriterij1 = new HashSet<Kriterij>();
            this.UsporedbaAlternativaPremaKriterijus = new HashSet<UsporedbaAlternativaPremaKriteriju>();
            this.UsporedbaKriterijas = new HashSet<UsporedbaKriterija>();
            this.UsporedbaKriterijas1 = new HashSet<UsporedbaKriterija>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public Nullable<int> idRoditelja { get; set; }
        public int projekt { get; set; }
        public Nullable<double> vrijednost { get; set; }
        public Nullable<bool> konzistentno { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> obrisan { get; set; }
        public string mjernaJedinica { get; set; }
        public Nullable<bool> konzistentneAlternative { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternativaKriterij> AlternativaKriterijs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kriterij> Kriterij1 { get; set; }
        public virtual Kriterij Kriterij2 { get; set; }
        public virtual Projekt Projekt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsporedbaAlternativaPremaKriteriju> UsporedbaAlternativaPremaKriterijus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsporedbaKriterija> UsporedbaKriterijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsporedbaKriterija> UsporedbaKriterijas1 { get; set; }
    }
}
