//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHPDecision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsporedbaAlternativaPremaKriteriju
    {
        public int kriterij { get; set; }
        public int alternativa1 { get; set; }
        public int alternativa2 { get; set; }
        public Nullable<double> vrijednost { get; set; }
    
        public virtual Alternativa Alternativa { get; set; }
        public virtual Alternativa Alternativa3 { get; set; }
        public virtual Kriterij Kriterij1 { get; set; }
    }
}
